@startuml AccountHandler
package server {
    class AccountHandler {
        - HikariDataSource dataSource
        + AccountHandler(HikariDataSource dataSource)
        + boolean signup(String nickname, String username, String email, String password)
        + boolean signin(String username, String password)
        + boolean deleteUser(String username, String password)
    }
}
@enduml
