@startuml server
!include ServerDriver.plantuml
!include ChatServer.plantuml
!include NotificationHandler.plantuml
!include ClientHandler.plantuml
!include AccountHandler.plantuml
!include ChatHandler.plantuml
!include ../shared/ChatRoom.plantuml
!include ../shared/Message.plantuml
!include ../shared/Container.plantuml


@enduml