@startuml Container

package shared {

    class Container {
        - static final long serialVersionUID = 42
        - String command
        - Object data

        + Container(String command, Object data)
        + String getCommand()
        + Object getData()
        + void setCommand(String command)
        + void setData(Object data)
        + String toString()
    }

}

@enduml
