@startuml Message

package shared {

    class Message {
        - String username
        - String type
        - String text
        - byte[] image
        - Timestamp timestamp
        + static final long serialVersionUID = 42L

        + Message(String username, String text, Timestamp timestamp)
        + Message(String username, byte[] image, Timestamp timestamp)
        + String toString()
    }
}

@enduml
